export const productsArr = [
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: false,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  },
  {
    image: 'productIcon.png',
    desc: 'Полное название товара в несколько строк для вида с обрывом в конце...',
    brand: 'беренд',
    price: 5990,
    sell: '25%',
    article: 'T1',
    available: true,
    category: 'Название категории',
    quantity: '1',
    size: 'атрибут'
  }
]
